spring.application.name=leads

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LeadDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Colombia2026*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
gemini.api.key=AIzaSyAvGr9W6Ni5E6ROgMru5i-ZsnqX1JJrdhY